---
title: "EpiFusion Framework Analysis Vignette (Complete Workflow, No Manuscript Text)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ape)
library(ggplot2)
library(ggtree)
library(ggpubr)
```

# EpiFusion Framework Analysis Vignette

The below Rmd script allows you to fully replicate the workflow outlined in the software article [insert title]. This code is also included in the Rmd with the full article text.

## Installation

```{r install_epifusionutilities}
devtools::install_github("https://github.com/ciarajudge/EpiFusionUtilities")
library(EpiFusionUtilities)
```

## Data Preparation

```{r load_data}
case_incidence <- read.csv("Data/Raw/weekly_incidence.csv") %>%
  mutate(Date = as.Date(Date))
fixed_tree <- read.tree("Data/Raw/fixed_tree.tree")
tree_posterior <- sample(read.nexus("Data/Raw/tree_posterior.trees")[2000:10000], 200) # Discard burn in, randomly sample 200
```

### Data

```{r plot_data}
tree_plotlims <- lubridate::decimal_date(as.Date(c("2023-12-24","2024-04-15"), format = "%Y-%m-%d"))

fixed_tree_plot <- ggtree(fixed_tree, mrsd = "2024-03-10", color = "darkslateblue") +
  xlim_tree(tree_plotlims) +
  geom_tippoint(col = "darkslateblue") +
  theme_tree2()

posterior_tree_plot <- ggdensitree(tree_posterior_subsample_for_plotting, color = "darkslateblue", alpha = 0.02) +
  xlim(-0.2149453, 0.101) +
  geom_tippoint(col = "darkslateblue") +
  theme_tree2()

case_incidence_plot <- ggplot(case_incidence, aes(x = Date, y = Cases)) +
  geom_point(col = "orangered3") +
  coord_cartesian(xlim = as.Date(c("2023-12-24", "2024-04-15")))

ggarrange(fixed_tree_plot, posterior_tree_plot, case_incidence_plot, ncol = 1, align = "v")
```

```{r set_index_date}
index_date <- as.Date("2023-12-15")
last_sequence <- as.Date("2024-03-10")
```

```{r prep_data}
fixed_tree <- prepare_epifusion_tree(fixed_tree, index_date, last_sequence, "Data/Processed/processed_fixed_tree.tree")
prepare_epifusion_tree(tree_posterior, index_date, last_sequence, "Data/Processed/processed_tree_posterior.tree")
```

```{r generate_epifusion_xml_fixed_tree}
loggers <- list(fileBase = "Results/fixed_tree", logEvery = 5)
parameters <- list(numParticles = 200, numSteps = 2000, numChains = 4, stepCoefficient = 0.05)
priors <- list(gamma = list(stepchange = "false",
                            disttype = "TruncatedNormal",
                            mean = 0.15,
                            standarddev = 0.03, 
                            lowerbound = 0.0),
               psi = list(stepchange = "false",
                            disttype = "TruncatedNormal",
                            mean = 0.001,
                            standarddev = 0.0004, 
                            lowerbound = 0.0),
               phi = list(stepchange = "false",
                            disttype = "TruncatedNormal",
                            mean = 0.02,
                            standarddev = 0.01, 
                            lowerbound = 0.0),
               initialBeta = list(stepchange = "false",
                            disttype = "Uniform",
                            min = 0.3,
                            max = 0.8),
               betaJitter = list(stepchange = "false",
                            disttype = "Uniform",
                            min = 0.001,
                            max = 0.1, 
                            lowerbound = 0.0))

generate_epifusion_XML(tree = "Data/Processed/processed_fixed_tree.tree",
                       case_incidence = case_incidence,
                       index_date = index_date,
                       loggers = loggers,
                       parameters = parameters,
                       priors = priors,
                       xml_filepath = "Data/EpiFusion_XMLs/fixed_tree_inputfile.xml")
```

```{r generate_epifusion_xml_tree_posterior}
loggers <- list(fileBase = "Results/tree_posterior_and_TOI", logEvery = 5)
parameters <- list(numParticles = 200, numSteps = 2000, numChains = 4, stepCoefficient = 0.05)
analysis <- list(type = "linearsplinebeta", inferTimeOfIntroduction = "true")
priors <- list(gamma = list(stepchange = "false",
                            disttype = "TruncatedNormal",
                            mean = 0.15,
                            standarddev = 0.03, 
                            lowerbound = 0.0),
               psi = list(stepchange = "false",
                            disttype = "TruncatedNormal",
                            mean = 0.001,
                            standarddev = 0.0004, 
                            lowerbound = 0.0),
               phi = list(stepchange = "false",
                            disttype = "TruncatedNormal",
                            mean = 0.02,
                            standarddev = 0.01, 
                            lowerbound = 0.0),
               initialBeta = list(stepchange = "false",
                            disttype = "Uniform",
                            min = 0.3,
                            max = 0.8),
               betaJitter = list(stepchange = "false",
                            disttype = "Uniform",
                            min = 0.001,
                            max = 0.1, 
                            lowerbound = 0.0),
               outbreakOrigin = list(stepchange = "false",
                            disttype = "UniformDiscrete",
                            min = 0,
                            max = 30, 
                            lowerbound = 0.0))

generate_epifusion_XML(tree = "Data/Processed/processed_tree_posterior.tree",
                       case_incidence = case_incidence,
                       index_date = index_date,
                       loggers = loggers,
                       parameters = parameters,
                       analysis = analysis,
                       priors = priors,
                       xml_filepath = "Data/EpiFusion_XMLs/tree_posterior_inputfile.xml")
```

```{r run_epifusion, eval = F}
#This code chunk is set to eval = F because it may be easier to run from command line
run_epifusion("Data/EpiFusion_XMLs/fixed_tree_inputfile.xml")
run_epifusion("Data/EpiFusion_XMLs/tree_posterior_inputfile.xml")
```


```{r parse_output_examine_trace}
raw_output_fixed <- load_raw_epifusion("Results/fixed_tree/")
plot_likelihood_trace(raw_output_fixed)

```

```{r extract_posteriors}
parsed_output_fixed <- extract_posterior_epifusion(raw_output_fixed, 0.1)

```

```{r plot_infection_trajectories}
traj_table <- trajectory_table(parsed_output, index_date)

ggplot(traj_table, aes(x = Time)) +
  geom_line(aes(y = Mean_Infected)) +
  geom_ribbon(aes(ymin = Lower95_Infected, ymax = Upper95_Infected), alpha = 0.2) +
  geom_ribbon(aes(ymin = Lower88_Infected, ymax = Upper88_Infected), alpha = 0.2) +
  geom_ribbon(aes(ymin = Lower66_Infected, ymax = Upper66_Infected), alpha = 0.2)

```

```{r plot_rt_trajectories}

ggplot(traj_table, aes(x = Time)) +
  geom_line(aes(y = Mean_Rt)) +
  geom_ribbon(aes(ymin = Lower95_Rt, ymax = Upper95_Rt), alpha = 0.2) +
  geom_ribbon(aes(ymin = Lower88_Rt, ymax = Upper88_Rt), alpha = 0.2) +
  geom_ribbon(aes(ymin = Lower66_Rt, ymax = Upper66_Rt), alpha = 0.2)

```


```{r plot_cuminfection_trajectories}

ggplot(traj_table, aes(x = Time)) +
  geom_line(aes(y = Mean_Rt)) +
  geom_ribbon(aes(ymin = Lower95_Rt, ymax = Upper95_Rt), alpha = 0.2) +
  geom_ribbon(aes(ymin = Lower88_Rt, ymax = Upper88_Rt), alpha = 0.2) +
  geom_ribbon(aes(ymin = Lower66_Rt, ymax = Upper66_Rt), alpha = 0.2)

```